//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ToyStoreEntities
{
    using System;
    using System.Collections.Generic;
    
    public partial class Toy
    {
        public Toy()
        {
            this.Categories = new HashSet<Category>();
        }
    
        public int id { get; set; }
        public string name { get; set; }
        public string type { get; set; }
        public int categoryId { get; set; }
        public int manufacturerId { get; set; }
        public decimal price { get; set; }
        public string color { get; set; }
        public int ageRangeId { get; set; }
    
        public virtual AgeRanx AgeRanx { get; set; }
        public virtual Manufacturer Manufacturer { get; set; }
        public virtual ICollection<Category> Categories { get; set; }
    }
}
